#!/usr/bin/env ruby
#
# Usage: gen-era-def.rb [era-defs.json] > lib/wareki/era_def.rb
#
# You can get era-defs.json from
# https://raw.githubusercontent.com/manakai/data-locale/master/data/calendar/era-defs.json
# (file argument omitted の場合は上記 URL から直接取得する)
#
# データ仕様: https://github.com/manakai/data-locale/blob/master/doc/calendar-era-defs.txt
#
require 'json'
require 'open-uri'
# インストール済み gem の wareki ではなく、このリポジトリの lib を確実に読む
$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'wareki/calendar'

class Wareki::EraDefGenerator
  SOURCE_URL = 'https://raw.githubusercontent.com/manakai/data-locale/master/data/calendar/era-defs.json'
  DAY_MAX_LITERAL = '1684383730585466947585'
  MEIJI_FIRST_YEAR = 1868

  Era = Struct.new(:name, :year, :start, :end)

  def initialize(io)
    defs = JSON.parse(io.read.force_encoding(Encoding::UTF_8))
    @eras = defs['eras'].each_value.select { |e|
      e['jp_era'] == 1 || e['jp_north_era'] == 1 || e['jp_south_era'] == 1
    }
    @eras.each do |e|
      e['name_ja'] && e['offset'] && e['start_day'] or
        raise "Missing required field: #{e['key']}"
    end
    kenmu = @eras.find { |e| e['key'] == '建武' } or raise 'Missing 建武'
    @split_start = jdn(kenmu['start_day'])
  end

  # manakai の jd は午前0時起点 (端数 0.5) なので +0.5 で暦日番号にする
  def jdn(day)
    Integer(day['jd'] + 0.5)
  end

  def south_only?(era)
    era['jp_south_era'] == 1 && era['jp_north_era'] != 1
  end

  # 建武の分裂以降に北朝が改元した元号 (暦応〜明徳)。分裂前から両朝共通の
  # 元号 (元徳・元弘・正慶・建武) は主系列に置く。
  def north_court?(era)
    era['jp_north_era'] == 1 && jdn(era['north_start_day']) > @split_start
  end

  def modern?(era)
    era['start_year'] >= MEIJI_FIRST_YEAR
  end

  # 明治のみ改元の詔により元年1月1日 (慶応4年1月1日) に遡って適用される
  def meiji_start
    Wareki::Calendar.to_jd(MEIJI_FIRST_YEAR, 1, 1, false)
  end

  # 明治より前は改元日当日を旧元号の末日としても含める (end = 次の改元日)。
  # 明治以降は一世一元で期間が重ならないため end はそのまま。
  def end_jdn(era, end_day)
    end_day or return 'DAY_MAX'
    modern?(era) ? jdn(end_day) : jdn(end_day) + 1
  end

  def build_era(era, start_day:, end_day:)
    Era.new(era['name_ja'], era['offset'] + 1, jdn(start_day), end_jdn(era, end_day))
  end

  # court: :south または :north。主系列の南北両属元号 (元徳・元弘・建武) は
  # start は共通で、終了のみ各朝の改元日で分かれる。
  def main_era(era, court)
    end_day = era["#{court}_end_day"] || era['end_day']
    e = build_era(era, start_day: era['start_day'], end_day: end_day)
    e.start = meiji_start if era['key'] == '明治'
    e
  end

  def court_era(era, court)
    build_era(era, start_day: era["#{court}_start_day"], end_day: era["#{court}_end_day"])
  end

  def era_list(court)
    souths, rest = @eras.partition { |e| south_only?(e) }
    norths, mains = rest.partition { |e| north_court?(e) }

    mains = mains.sort_by { |e| jdn(e['start_day']) }.map { |e| main_era(e, court) }
    souths = souths.sort_by { |e| jdn(e['south_start_day']) }.map { |e| court_era(e, :south) }
    norths = norths.sort_by { |e| jdn(e['north_start_day']) }.map { |e| court_era(e, :north) }

    pre_split, post_split = mains.partition { |e| e.start <= @split_start }
    pre_split + souths + norths + post_split
  end

  def generate(out = $stdout)
    out.puts '# frozen_string_literal: true'
    out.puts '# coding: utf-8'
    out.puts ''
    out.puts '# Generated by build-util/gen-era-def.rb from manakai data-locale era-defs.json.'
    out.puts '# Do not edit this file directly.'
    out.puts 'module Wareki'
    out.puts "  DAY_MAX = #{DAY_MAX_LITERAL}"
    out.puts '  Era = Struct.new(:name, :year, :start, :end)'
    { 'ERA_DEFS' => :south, 'ERA_NORTH_DEFS' => :north }.each do |label, court|
      out.puts "  #{label} = ["
      era_list(court).each do |e|
        out.puts %Q{    Era.new("#{e.name}", #{e.year}, #{e.start}, #{e.end}),}
      end
      out.puts '  ].each(&:freeze).freeze'
    end
    out.puts 'end'
  end
end

if $0 == __FILE__
  io = ARGV.first ? File.open(ARGV.first) : URI.open(Wareki::EraDefGenerator::SOURCE_URL)
  Wareki::EraDefGenerator.new(io).generate
end
